#!/bin/bash

set -e

sources=("assembled" "static")
html_branch="gh-pages"

if ! git diff --quiet --exit-code; then
  >&2 echo "There are local changes - aborting"
  exit
fi

if ! git rev-parse "$html_branch" -- &>/dev/null; then
  git checkout --orphan "$html_branch"
else
  git checkout -q "$html_branch"
fi

git rm -rfq .

for dir in "${sources[@]}"; do
  git checkout -q master -- "$dir"
  mv "$dir"/* .
  git rm -rfq "$dir"
done

git add *
git commit -m "Update" || true
git checkout -q master
